// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mqtt/common.proto

package omo_msp_mqtt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Flag                 string   `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{0}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type RequestFilter struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32   `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Values               []string `protobuf:"bytes,7,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFilter) Reset()         { *m = RequestFilter{} }
func (m *RequestFilter) String() string { return proto.CompactTextString(m) }
func (*RequestFilter) ProtoMessage()    {}
func (*RequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{1}
}

func (m *RequestFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFilter.Unmarshal(m, b)
}
func (m *RequestFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFilter.Marshal(b, m, deterministic)
}
func (m *RequestFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFilter.Merge(m, src)
}
func (m *RequestFilter) XXX_Size() int {
	return xxx_messageInfo_RequestFilter.Size(m)
}
func (m *RequestFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFilter.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFilter proto.InternalMessageInfo

func (m *RequestFilter) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RequestFilter) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *RequestFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestFilter) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestFilter) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestFilter) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestFilter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type RequestUpdate struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Values               []string `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUpdate) Reset()         { *m = RequestUpdate{} }
func (m *RequestUpdate) String() string { return proto.CompactTextString(m) }
func (*RequestUpdate) ProtoMessage()    {}
func (*RequestUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{2}
}

func (m *RequestUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUpdate.Unmarshal(m, b)
}
func (m *RequestUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUpdate.Marshal(b, m, deterministic)
}
func (m *RequestUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUpdate.Merge(m, src)
}
func (m *RequestUpdate) XXX_Size() int {
	return xxx_messageInfo_RequestUpdate.Size(m)
}
func (m *RequestUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUpdate proto.InternalMessageInfo

func (m *RequestUpdate) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RequestUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestUpdate) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *RequestUpdate) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestUpdate) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ReplyStatus struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{3}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplyStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SocketInfo struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Skip                 uint32   `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Begin                uint32   `protobuf:"varint,4,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint32   `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
	Status               uint32   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Weeks                []uint32 `protobuf:"varint,10,rep,packed,name=weeks,proto3" json:"weeks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocketInfo) Reset()         { *m = SocketInfo{} }
func (m *SocketInfo) String() string { return proto.CompactTextString(m) }
func (*SocketInfo) ProtoMessage()    {}
func (*SocketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{4}
}

func (m *SocketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketInfo.Unmarshal(m, b)
}
func (m *SocketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketInfo.Marshal(b, m, deterministic)
}
func (m *SocketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketInfo.Merge(m, src)
}
func (m *SocketInfo) XXX_Size() int {
	return xxx_messageInfo_SocketInfo.Size(m)
}
func (m *SocketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SocketInfo proto.InternalMessageInfo

func (m *SocketInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SocketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SocketInfo) GetSkip() uint32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *SocketInfo) GetBegin() uint32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *SocketInfo) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *SocketInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SocketInfo) GetWeeks() []uint32 {
	if m != nil {
		return m.Weeks
	}
	return nil
}

type ReplyInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{5}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RequestIntFlag struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Flag                 int32    `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestIntFlag) Reset()         { *m = RequestIntFlag{} }
func (m *RequestIntFlag) String() string { return proto.CompactTextString(m) }
func (*RequestIntFlag) ProtoMessage()    {}
func (*RequestIntFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{6}
}

func (m *RequestIntFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestIntFlag.Unmarshal(m, b)
}
func (m *RequestIntFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestIntFlag.Marshal(b, m, deterministic)
}
func (m *RequestIntFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestIntFlag.Merge(m, src)
}
func (m *RequestIntFlag) XXX_Size() int {
	return xxx_messageInfo_RequestIntFlag.Size(m)
}
func (m *RequestIntFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestIntFlag.DiscardUnknown(m)
}

var xxx_messageInfo_RequestIntFlag proto.InternalMessageInfo

func (m *RequestIntFlag) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestIntFlag) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *RequestIntFlag) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestList struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []string `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestList) Reset()         { *m = RequestList{} }
func (m *RequestList) String() string { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()    {}
func (*RequestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{7}
}

func (m *RequestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestList.Unmarshal(m, b)
}
func (m *RequestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestList.Marshal(b, m, deterministic)
}
func (m *RequestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestList.Merge(m, src)
}
func (m *RequestList) XXX_Size() int {
	return xxx_messageInfo_RequestList.Size(m)
}
func (m *RequestList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestList proto.InternalMessageInfo

func (m *RequestList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestList) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyList struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	List                 []string     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyList) Reset()         { *m = ReplyList{} }
func (m *ReplyList) String() string { return proto.CompactTextString(m) }
func (*ReplyList) ProtoMessage()    {}
func (*ReplyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{8}
}

func (m *ReplyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyList.Unmarshal(m, b)
}
func (m *ReplyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyList.Marshal(b, m, deterministic)
}
func (m *ReplyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyList.Merge(m, src)
}
func (m *ReplyList) XXX_Size() int {
	return xxx_messageInfo_ReplyList.Size(m)
}
func (m *ReplyList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyList proto.InternalMessageInfo

func (m *ReplyList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyStatistic struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Key                  string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Owner                string       `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Count                uint32       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStatistic) Reset()         { *m = ReplyStatistic{} }
func (m *ReplyStatistic) String() string { return proto.CompactTextString(m) }
func (*ReplyStatistic) ProtoMessage()    {}
func (*ReplyStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ac4d88d62e40be, []int{9}
}

func (m *ReplyStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatistic.Unmarshal(m, b)
}
func (m *ReplyStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatistic.Marshal(b, m, deterministic)
}
func (m *ReplyStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatistic.Merge(m, src)
}
func (m *ReplyStatistic) XXX_Size() int {
	return xxx_messageInfo_ReplyStatistic.Size(m)
}
func (m *ReplyStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatistic proto.InternalMessageInfo

func (m *ReplyStatistic) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStatistic) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReplyStatistic) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReplyStatistic) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.mqtt.RequestInfo")
	proto.RegisterType((*RequestFilter)(nil), "omo.msp.mqtt.RequestFilter")
	proto.RegisterType((*RequestUpdate)(nil), "omo.msp.mqtt.RequestUpdate")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.mqtt.ReplyStatus")
	proto.RegisterType((*SocketInfo)(nil), "omo.msp.mqtt.SocketInfo")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.mqtt.ReplyInfo")
	proto.RegisterType((*RequestIntFlag)(nil), "omo.msp.mqtt.RequestIntFlag")
	proto.RegisterType((*RequestList)(nil), "omo.msp.mqtt.RequestList")
	proto.RegisterType((*ReplyList)(nil), "omo.msp.mqtt.ReplyList")
	proto.RegisterType((*ReplyStatistic)(nil), "omo.msp.mqtt.ReplyStatistic")
}

func init() {
	proto.RegisterFile("proto/mqtt/common.proto", fileDescriptor_39ac4d88d62e40be)
}

var fileDescriptor_39ac4d88d62e40be = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0xc4, 0x90, 0x3d, 0x8c, 0x90, 0x85, 0x0e, 0x1f, 0x55, 0xe4, 0xea, 0x2a, 0x9f,
	0x80, 0x82, 0x82, 0x8e, 0xe2, 0x24, 0x24, 0x24, 0xd0, 0x9e, 0x68, 0x68, 0x4e, 0x8e, 0x3d, 0x89,
	0x56, 0xf6, 0x7a, 0x7d, 0xbb, 0x6b, 0xa2, 0x94, 0xfc, 0x0a, 0x1a, 0xfe, 0x04, 0xff, 0x10, 0xcd,
	0x78, 0xed, 0x38, 0xc7, 0x85, 0x4b, 0x37, 0x6f, 0xe2, 0xf9, 0x78, 0x6f, 0xde, 0x86, 0xbd, 0x6a,
	0xb5, 0xb2, 0xea, 0x4a, 0xde, 0x59, 0x7b, 0x55, 0x28, 0x29, 0x55, 0x93, 0x51, 0x26, 0x7e, 0xa6,
	0xa4, 0xca, 0xa4, 0x69, 0x33, 0xfc, 0x29, 0xdd, 0xb2, 0x33, 0x0e, 0x77, 0x1d, 0x18, 0xfb, 0xa9,
	0x59, 0xab, 0xf8, 0x05, 0x0b, 0x3a, 0x51, 0x26, 0xde, 0xd2, 0xbb, 0x5c, 0x70, 0x0c, 0xe3, 0x98,
	0xcd, 0xd6, 0x75, 0xbe, 0x49, 0x7c, 0x4a, 0x51, 0x1c, 0xbf, 0x66, 0x4f, 0x55, 0x0b, 0x3a, 0xb7,
	0x4a, 0x27, 0x01, 0xe5, 0x47, 0x8c, 0xdf, 0x37, 0xb9, 0x84, 0x64, 0xd6, 0x7f, 0x8f, 0x31, 0xe6,
	0x3a, 0x03, 0x3a, 0x99, 0xf7, 0x39, 0x8c, 0xd3, 0x3f, 0x1e, 0x8b, 0xdc, 0xe4, 0x6b, 0x51, 0x5b,
	0xd0, 0xf1, 0x4b, 0x36, 0x57, 0xdb, 0x06, 0xb4, 0x9b, 0xde, 0x03, 0xcc, 0xae, 0x05, 0xd4, 0xa5,
	0x5b, 0xa0, 0x07, 0x98, 0xfd, 0x91, 0xd7, 0x1d, 0xb8, 0xf1, 0x3d, 0xc0, 0x39, 0x6d, 0xbe, 0xe9,
	0x67, 0x47, 0x9c, 0xe2, 0xf8, 0x9c, 0x85, 0x4d, 0x27, 0x57, 0x6e, 0x7a, 0xc4, 0x1d, 0x3a, 0xe0,
	0x10, 0xde, 0xe3, 0x70, 0xce, 0x42, 0x6a, 0x68, 0x92, 0x27, 0xcb, 0xe0, 0x72, 0xc1, 0x1d, 0x4a,
	0x7f, 0xed, 0x77, 0xfe, 0xd6, 0x96, 0xb9, 0x85, 0x23, 0x3b, 0x3b, 0x15, 0xfd, 0xbd, 0x8a, 0x23,
	0x8b, 0xe0, 0x41, 0x16, 0xb3, 0x29, 0x8b, 0xe9, 0x66, 0xf3, 0xa3, 0x9b, 0x85, 0x07, 0x9b, 0xbd,
	0xc7, 0x33, 0xb6, 0xf5, 0xee, 0xc6, 0xe6, 0xb6, 0x33, 0x28, 0x44, 0xa1, 0x4a, 0xa0, 0xad, 0x22,
	0x4e, 0x31, 0x0e, 0x03, 0xad, 0x95, 0x1e, 0x84, 0x24, 0x90, 0xfe, 0xf6, 0x18, 0xbb, 0x51, 0x45,
	0x05, 0xe3, 0xfd, 0x2b, 0xd8, 0x0d, 0xf7, 0xaf, 0x60, 0x37, 0xde, 0xd3, 0x3f, 0xbc, 0xa7, 0xa9,
	0x44, 0x4b, 0x64, 0x22, 0x4e, 0x31, 0xb6, 0x5f, 0xc1, 0x46, 0x34, 0x4e, 0xfc, 0x1e, 0x60, 0x3f,
	0x68, 0x4a, 0x27, 0x3d, 0x86, 0xc8, 0xc0, 0xd0, 0x92, 0xa4, 0x7a, 0xc4, 0x1d, 0xc2, 0xfa, 0x2d,
	0x40, 0x65, 0x12, 0xb6, 0x0c, 0xb0, 0x9e, 0x40, 0xfa, 0x95, 0x2d, 0x88, 0xd7, 0x11, 0x73, 0xbe,
	0x19, 0x9b, 0xe1, 0x7a, 0x67, 0x6f, 0x2f, 0xb2, 0xa9, 0xb9, 0xb3, 0x89, 0x24, 0xc3, 0x9c, 0x94,
	0xb3, 0xe7, 0xa3, 0xe1, 0xed, 0x35, 0xba, 0xf9, 0xff, 0x9e, 0x9f, 0x3f, 0xee, 0xf9, 0xf4, 0xcb,
	0xf8, 0x88, 0x3e, 0x0b, 0x63, 0x1f, 0x68, 0x38, 0x2d, 0xf6, 0xff, 0x7d, 0x30, 0xb5, 0x30, 0x36,
	0x09, 0xe8, 0xa0, 0x14, 0xa7, 0xa5, 0xa3, 0x7d, 0xa4, 0xdd, 0x50, 0xe2, 0xef, 0x4b, 0x26, 0x52,
	0x04, 0xa7, 0x4a, 0xf1, 0xd3, 0x43, 0x2d, 0x5c, 0x5e, 0x18, 0x2b, 0x8a, 0x49, 0x17, 0xef, 0xc4,
	0x2e, 0x83, 0x65, 0xfc, 0xbd, 0x65, 0xc6, 0x47, 0x11, 0xdc, 0x7b, 0xc8, 0x85, 0xea, 0x1a, 0x3b,
	0x18, 0x84, 0xc0, 0xc7, 0x8b, 0xef, 0x93, 0x3f, 0xaa, 0x0f, 0x4a, 0xaa, 0x5b, 0x69, 0xda, 0x5b,
	0x04, 0xab, 0x90, 0x7e, 0x78, 0xf7, 0x37, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x26, 0xb8, 0x1d, 0xca,
	0x04, 0x00, 0x00,
}
