// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mqtt/plug.proto

package omo_msp_mqtt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlugInfo struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64           `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64           `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string          `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string          `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string          `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string          `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Area                 string          `protobuf:"bytes,9,opt,name=area,proto3" json:"area,omitempty"`
	Scene                string          `protobuf:"bytes,10,opt,name=scene,proto3" json:"scene,omitempty"`
	Device               string          `protobuf:"bytes,11,opt,name=device,proto3" json:"device,omitempty"`
	Heartbeat            uint32          `protobuf:"varint,12,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Contact              string          `protobuf:"bytes,13,opt,name=contact,proto3" json:"contact,omitempty"`
	Online               uint32          `protobuf:"varint,14,opt,name=online,proto3" json:"online,omitempty"`
	Kind                 uint32          `protobuf:"varint,15,opt,name=kind,proto3" json:"kind,omitempty"`
	Network              uint32          `protobuf:"varint,16,opt,name=network,proto3" json:"network,omitempty"`
	Status               *PlugStatusInfo `protobuf:"bytes,17,opt,name=status,proto3" json:"status,omitempty"`
	Sockets              []*SocketInfo   `protobuf:"bytes,21,rep,name=sockets,proto3" json:"sockets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlugInfo) Reset()         { *m = PlugInfo{} }
func (m *PlugInfo) String() string { return proto.CompactTextString(m) }
func (*PlugInfo) ProtoMessage()    {}
func (*PlugInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{0}
}

func (m *PlugInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlugInfo.Unmarshal(m, b)
}
func (m *PlugInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlugInfo.Marshal(b, m, deterministic)
}
func (m *PlugInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlugInfo.Merge(m, src)
}
func (m *PlugInfo) XXX_Size() int {
	return xxx_messageInfo_PlugInfo.Size(m)
}
func (m *PlugInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlugInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlugInfo proto.InternalMessageInfo

func (m *PlugInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PlugInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlugInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PlugInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *PlugInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PlugInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *PlugInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlugInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *PlugInfo) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *PlugInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *PlugInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *PlugInfo) GetHeartbeat() uint32 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

func (m *PlugInfo) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *PlugInfo) GetOnline() uint32 {
	if m != nil {
		return m.Online
	}
	return 0
}

func (m *PlugInfo) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *PlugInfo) GetNetwork() uint32 {
	if m != nil {
		return m.Network
	}
	return 0
}

func (m *PlugInfo) GetStatus() *PlugStatusInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PlugInfo) GetSockets() []*SocketInfo {
	if m != nil {
		return m.Sockets
	}
	return nil
}

type PlugStatusInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Device               string   `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Power                uint32   `protobuf:"varint,3,opt,name=power,proto3" json:"power,omitempty"`
	Smoke                string   `protobuf:"bytes,4,opt,name=smoke,proto3" json:"smoke,omitempty"`
	Temper               float32  `protobuf:"fixed32,5,opt,name=temper,proto3" json:"temper,omitempty"`
	Scene                string   `protobuf:"bytes,6,opt,name=scene,proto3" json:"scene,omitempty"`
	Area                 string   `protobuf:"bytes,7,opt,name=area,proto3" json:"area,omitempty"`
	Updated              int64    `protobuf:"varint,8,opt,name=updated,proto3" json:"updated,omitempty"`
	Online               uint32   `protobuf:"varint,9,opt,name=online,proto3" json:"online,omitempty"`
	Network              uint32   `protobuf:"varint,10,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlugStatusInfo) Reset()         { *m = PlugStatusInfo{} }
func (m *PlugStatusInfo) String() string { return proto.CompactTextString(m) }
func (*PlugStatusInfo) ProtoMessage()    {}
func (*PlugStatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{1}
}

func (m *PlugStatusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlugStatusInfo.Unmarshal(m, b)
}
func (m *PlugStatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlugStatusInfo.Marshal(b, m, deterministic)
}
func (m *PlugStatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlugStatusInfo.Merge(m, src)
}
func (m *PlugStatusInfo) XXX_Size() int {
	return xxx_messageInfo_PlugStatusInfo.Size(m)
}
func (m *PlugStatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlugStatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlugStatusInfo proto.InternalMessageInfo

func (m *PlugStatusInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PlugStatusInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *PlugStatusInfo) GetPower() uint32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *PlugStatusInfo) GetSmoke() string {
	if m != nil {
		return m.Smoke
	}
	return ""
}

func (m *PlugStatusInfo) GetTemper() float32 {
	if m != nil {
		return m.Temper
	}
	return 0
}

func (m *PlugStatusInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *PlugStatusInfo) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *PlugStatusInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *PlugStatusInfo) GetOnline() uint32 {
	if m != nil {
		return m.Online
	}
	return 0
}

func (m *PlugStatusInfo) GetNetwork() uint32 {
	if m != nil {
		return m.Network
	}
	return 0
}

type ReqPlugAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scene                string   `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Area                 string   `protobuf:"bytes,4,opt,name=area,proto3" json:"area,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Device               string   `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Contact              string   `protobuf:"bytes,7,opt,name=contact,proto3" json:"contact,omitempty"`
	Heartbeat            uint32   `protobuf:"varint,13,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Kind                 uint32   `protobuf:"varint,14,opt,name=kind,proto3" json:"kind,omitempty"`
	Sockets              []string `protobuf:"bytes,21,rep,name=sockets,proto3" json:"sockets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPlugAdd) Reset()         { *m = ReqPlugAdd{} }
func (m *ReqPlugAdd) String() string { return proto.CompactTextString(m) }
func (*ReqPlugAdd) ProtoMessage()    {}
func (*ReqPlugAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{2}
}

func (m *ReqPlugAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPlugAdd.Unmarshal(m, b)
}
func (m *ReqPlugAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPlugAdd.Marshal(b, m, deterministic)
}
func (m *ReqPlugAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPlugAdd.Merge(m, src)
}
func (m *ReqPlugAdd) XXX_Size() int {
	return xxx_messageInfo_ReqPlugAdd.Size(m)
}
func (m *ReqPlugAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPlugAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPlugAdd proto.InternalMessageInfo

func (m *ReqPlugAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPlugAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqPlugAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPlugAdd) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *ReqPlugAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPlugAdd) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *ReqPlugAdd) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ReqPlugAdd) GetHeartbeat() uint32 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

func (m *ReqPlugAdd) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ReqPlugAdd) GetSockets() []string {
	if m != nil {
		return m.Sockets
	}
	return nil
}

type ReqPlugSocket struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Begin                uint32   `protobuf:"varint,4,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint32   `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
	Skip                 uint32   `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Operator             string   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Weeks                []uint32 `protobuf:"varint,10,rep,packed,name=weeks,proto3" json:"weeks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPlugSocket) Reset()         { *m = ReqPlugSocket{} }
func (m *ReqPlugSocket) String() string { return proto.CompactTextString(m) }
func (*ReqPlugSocket) ProtoMessage()    {}
func (*ReqPlugSocket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{3}
}

func (m *ReqPlugSocket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPlugSocket.Unmarshal(m, b)
}
func (m *ReqPlugSocket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPlugSocket.Marshal(b, m, deterministic)
}
func (m *ReqPlugSocket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPlugSocket.Merge(m, src)
}
func (m *ReqPlugSocket) XXX_Size() int {
	return xxx_messageInfo_ReqPlugSocket.Size(m)
}
func (m *ReqPlugSocket) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPlugSocket.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPlugSocket proto.InternalMessageInfo

func (m *ReqPlugSocket) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPlugSocket) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqPlugSocket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPlugSocket) GetBegin() uint32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *ReqPlugSocket) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *ReqPlugSocket) GetSkip() uint32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ReqPlugSocket) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqPlugSocket) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPlugSocket) GetWeeks() []uint32 {
	if m != nil {
		return m.Weeks
	}
	return nil
}

type ReqPlugUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Contact              string   `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	Flag                 string   `protobuf:"bytes,6,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPlugUpdate) Reset()         { *m = ReqPlugUpdate{} }
func (m *ReqPlugUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqPlugUpdate) ProtoMessage()    {}
func (*ReqPlugUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{4}
}

func (m *ReqPlugUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPlugUpdate.Unmarshal(m, b)
}
func (m *ReqPlugUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPlugUpdate.Marshal(b, m, deterministic)
}
func (m *ReqPlugUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPlugUpdate.Merge(m, src)
}
func (m *ReqPlugUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqPlugUpdate.Size(m)
}
func (m *ReqPlugUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPlugUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPlugUpdate proto.InternalMessageInfo

func (m *ReqPlugUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPlugUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPlugUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPlugUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPlugUpdate) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ReqPlugUpdate) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

type ReplyPlugOne struct {
	Info                 *PlugInfo    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyPlugOne) Reset()         { *m = ReplyPlugOne{} }
func (m *ReplyPlugOne) String() string { return proto.CompactTextString(m) }
func (*ReplyPlugOne) ProtoMessage()    {}
func (*ReplyPlugOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{5}
}

func (m *ReplyPlugOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPlugOne.Unmarshal(m, b)
}
func (m *ReplyPlugOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPlugOne.Marshal(b, m, deterministic)
}
func (m *ReplyPlugOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPlugOne.Merge(m, src)
}
func (m *ReplyPlugOne) XXX_Size() int {
	return xxx_messageInfo_ReplyPlugOne.Size(m)
}
func (m *ReplyPlugOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPlugOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPlugOne proto.InternalMessageInfo

func (m *ReplyPlugOne) GetInfo() *PlugInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyPlugOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyPlugList struct {
	Total                uint32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32       `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32       `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*PlugInfo  `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyPlugList) Reset()         { *m = ReplyPlugList{} }
func (m *ReplyPlugList) String() string { return proto.CompactTextString(m) }
func (*ReplyPlugList) ProtoMessage()    {}
func (*ReplyPlugList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{6}
}

func (m *ReplyPlugList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPlugList.Unmarshal(m, b)
}
func (m *ReplyPlugList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPlugList.Marshal(b, m, deterministic)
}
func (m *ReplyPlugList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPlugList.Merge(m, src)
}
func (m *ReplyPlugList) XXX_Size() int {
	return xxx_messageInfo_ReplyPlugList.Size(m)
}
func (m *ReplyPlugList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPlugList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPlugList proto.InternalMessageInfo

func (m *ReplyPlugList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyPlugList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyPlugList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyPlugList) GetList() []*PlugInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyPlugList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyPlugStatus struct {
	Status               *ReplyStatus      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32            `protobuf:"varint,3,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32            `protobuf:"varint,4,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*PlugStatusInfo `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplyPlugStatus) Reset()         { *m = ReplyPlugStatus{} }
func (m *ReplyPlugStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyPlugStatus) ProtoMessage()    {}
func (*ReplyPlugStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1679862d436e7c, []int{7}
}

func (m *ReplyPlugStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPlugStatus.Unmarshal(m, b)
}
func (m *ReplyPlugStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPlugStatus.Marshal(b, m, deterministic)
}
func (m *ReplyPlugStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPlugStatus.Merge(m, src)
}
func (m *ReplyPlugStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyPlugStatus.Size(m)
}
func (m *ReplyPlugStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPlugStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPlugStatus proto.InternalMessageInfo

func (m *ReplyPlugStatus) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPlugStatus) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyPlugStatus) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyPlugStatus) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyPlugStatus) GetList() []*PlugStatusInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*PlugInfo)(nil), "omo.msp.mqtt.PlugInfo")
	proto.RegisterType((*PlugStatusInfo)(nil), "omo.msp.mqtt.PlugStatusInfo")
	proto.RegisterType((*ReqPlugAdd)(nil), "omo.msp.mqtt.ReqPlugAdd")
	proto.RegisterType((*ReqPlugSocket)(nil), "omo.msp.mqtt.ReqPlugSocket")
	proto.RegisterType((*ReqPlugUpdate)(nil), "omo.msp.mqtt.ReqPlugUpdate")
	proto.RegisterType((*ReplyPlugOne)(nil), "omo.msp.mqtt.ReplyPlugOne")
	proto.RegisterType((*ReplyPlugList)(nil), "omo.msp.mqtt.ReplyPlugList")
	proto.RegisterType((*ReplyPlugStatus)(nil), "omo.msp.mqtt.ReplyPlugStatus")
}

func init() {
	proto.RegisterFile("proto/mqtt/plug.proto", fileDescriptor_2e1679862d436e7c)
}

var fileDescriptor_2e1679862d436e7c = []byte{
	// 909 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xbd, 0x6e, 0xe3, 0x46,
	0x10, 0x36, 0x7f, 0xf4, 0x37, 0x12, 0x75, 0xce, 0xc2, 0x77, 0xb7, 0xa7, 0xbb, 0x00, 0x02, 0x2b,
	0x21, 0x85, 0x2e, 0x51, 0xd2, 0xa5, 0x89, 0x5d, 0xc4, 0x30, 0x72, 0xf9, 0x01, 0x0f, 0x69, 0xd2,
	0x1c, 0x68, 0x71, 0xac, 0x10, 0x12, 0xb9, 0x34, 0xb9, 0x3a, 0xc7, 0x4f, 0x92, 0x57, 0x49, 0x99,
	0x17, 0x08, 0xf2, 0x22, 0x29, 0x53, 0xa6, 0x08, 0x76, 0x76, 0x29, 0x92, 0x32, 0x25, 0xbb, 0xdb,
	0xd9, 0x99, 0xfd, 0x38, 0xdf, 0x37, 0xdf, 0x2e, 0x08, 0xcf, 0xb3, 0x5c, 0x48, 0xf1, 0x36, 0xb9,
	0x95, 0xf2, 0x6d, 0xb6, 0xd9, 0xae, 0xe6, 0x14, 0xb3, 0x91, 0x48, 0xc4, 0x3c, 0x29, 0xb2, 0xb9,
	0x4a, 0x4c, 0x5e, 0xd6, 0x8a, 0x96, 0x22, 0x49, 0x44, 0xaa, 0xcb, 0xfc, 0x7f, 0x1c, 0xe8, 0xff,
	0xb4, 0xd9, 0xae, 0xae, 0xd2, 0x1b, 0xc1, 0x4e, 0xc1, 0xd9, 0xc6, 0x11, 0xb7, 0xa6, 0xd6, 0x6c,
	0x10, 0xa8, 0x25, 0x1b, 0x83, 0x1d, 0x47, 0xdc, 0x9e, 0x5a, 0x33, 0x37, 0xb0, 0xe3, 0x88, 0x71,
	0xe8, 0x2d, 0x73, 0x0c, 0x25, 0x46, 0xdc, 0x99, 0x5a, 0x33, 0x27, 0x28, 0x43, 0x95, 0xd9, 0x66,
	0x11, 0x65, 0x5c, 0x9d, 0x31, 0xe1, 0xee, 0x8c, 0xc8, 0x79, 0x87, 0x90, 0xcb, 0x90, 0x4d, 0xa0,
	0x2f, 0x32, 0xcc, 0x29, 0xd5, 0xa5, 0xd4, 0x2e, 0x66, 0x0c, 0xdc, 0x34, 0x4c, 0x90, 0xf7, 0x68,
	0x9f, 0xd6, 0xec, 0x05, 0x74, 0x73, 0x4c, 0xc2, 0x7c, 0xcd, 0xfb, 0xb4, 0x6b, 0x22, 0x55, 0x1b,
	0xe6, 0x18, 0xf2, 0x81, 0xae, 0x55, 0x6b, 0x76, 0x06, 0x9d, 0x62, 0x89, 0x29, 0x72, 0xa0, 0x4d,
	0x1d, 0x28, 0x84, 0x08, 0x3f, 0xc6, 0x4b, 0xe4, 0x43, 0x8d, 0xa0, 0x23, 0xf6, 0x06, 0x06, 0xbf,
	0x62, 0x98, 0xcb, 0x6b, 0x0c, 0x25, 0x1f, 0x4d, 0xad, 0x99, 0x17, 0x54, 0x1b, 0xc4, 0x40, 0xa4,
	0x32, 0x5c, 0x4a, 0xee, 0x19, 0x06, 0x3a, 0x54, 0x78, 0x22, 0xdd, 0xc4, 0x29, 0xf2, 0x31, 0x1d,
	0x32, 0x91, 0xea, 0x68, 0x1d, 0xa7, 0x11, 0x7f, 0x46, 0xbb, 0xb4, 0x56, 0x28, 0x29, 0xca, 0x3b,
	0x91, 0xaf, 0xf9, 0x29, 0x6d, 0x97, 0x21, 0xfb, 0x0a, 0xba, 0x85, 0x0c, 0xe5, 0xb6, 0xe0, 0x9f,
	0x4c, 0xad, 0xd9, 0x70, 0xf1, 0x66, 0x5e, 0x1f, 0xde, 0x5c, 0xcd, 0xe7, 0x3d, 0xe5, 0xd5, 0x94,
	0x02, 0x53, 0xcb, 0x16, 0xd0, 0x2b, 0xc4, 0x72, 0x8d, 0xb2, 0xe0, 0xcf, 0xa7, 0xce, 0x6c, 0xb8,
	0xe0, 0xcd, 0x63, 0xef, 0x29, 0x49, 0x47, 0xca, 0x42, 0xff, 0x5f, 0x0b, 0xc6, 0x4d, 0xb8, 0x96,
	0xa1, 0x57, 0x22, 0xd9, 0x0d, 0x91, 0xce, 0xa0, 0x93, 0x89, 0x3b, 0xcc, 0x69, 0xf4, 0x5e, 0xa0,
	0x03, 0x12, 0x3a, 0x11, 0x6b, 0xa4, 0xb1, 0x2b, 0xa1, 0x55, 0xa0, 0x30, 0x24, 0x26, 0x19, 0xea,
	0x99, 0xdb, 0x81, 0x89, 0xaa, 0xb1, 0x74, 0xeb, 0x63, 0x29, 0x07, 0xd8, 0xab, 0x0d, 0xb0, 0x66,
	0xa8, 0x7e, 0xd3, 0x50, 0x95, 0xe8, 0x83, 0x86, 0xe8, 0x35, 0x81, 0xa1, 0x21, 0xb0, 0xff, 0x9f,
	0x05, 0x10, 0xe0, 0xad, 0x62, 0x7e, 0x1e, 0x45, 0x3b, 0x6f, 0x59, 0x35, 0x6f, 0xed, 0x1a, 0xb3,
	0xf7, 0xfc, 0x62, 0x1c, 0xe7, 0xb4, 0x3a, 0xce, 0xad, 0x35, 0x5c, 0x77, 0x73, 0x67, 0xcf, 0xcd,
	0x95, 0xa4, 0xdd, 0x86, 0xa4, 0x35, 0x67, 0xf5, 0x9a, 0xce, 0x6a, 0x38, 0xd2, 0xdb, 0x77, 0x64,
	0xe9, 0xaf, 0x71, 0xd3, 0x5f, 0x75, 0x3f, 0x0c, 0xaa, 0xa9, 0xff, 0x65, 0x81, 0x67, 0xe8, 0x6b,
	0x53, 0xb4, 0x0c, 0xfd, 0x14, 0x9c, 0x35, 0xde, 0x1b, 0xf6, 0x6a, 0xb9, 0x53, 0xc9, 0x69, 0xaa,
	0x74, 0x8d, 0xab, 0x38, 0x25, 0xe2, 0x5e, 0xa0, 0x03, 0x75, 0x16, 0xd3, 0x88, 0x48, 0x7b, 0x81,
	0x5a, 0xaa, 0xb3, 0xc5, 0x3a, 0xce, 0x88, 0xad, 0x17, 0xd0, 0x5a, 0x69, 0x60, 0x5c, 0xde, 0xd3,
	0x63, 0x33, 0x3e, 0xae, 0xeb, 0xd6, 0xdf, 0xd3, 0xed, 0x0c, 0x3a, 0x77, 0x88, 0xeb, 0x82, 0xc3,
	0xd4, 0x51, 0xdf, 0xa3, 0xc0, 0xff, 0xbd, 0xe2, 0xf3, 0x33, 0x79, 0xa2, 0x85, 0x4f, 0xd9, 0xbd,
	0xdd, 0xfa, 0x7e, 0x34, 0xa7, 0x59, 0xef, 0xc0, 0xdd, 0xeb, 0xa0, 0x36, 0xa1, 0x4e, 0x73, 0x42,
	0x0c, 0xdc, 0x9b, 0x4d, 0xb8, 0x32, 0x13, 0xa5, 0xb5, 0x9f, 0xc0, 0x28, 0xc0, 0x6c, 0x73, 0xaf,
	0x5a, 0xfb, 0x31, 0x45, 0xf6, 0x19, 0xb8, 0x71, 0x7a, 0x23, 0xa8, 0xb1, 0xe1, 0xe2, 0xc5, 0xc3,
	0x7b, 0x4d, 0xd7, 0x93, 0x6a, 0xd8, 0x17, 0x3b, 0x7d, 0x6c, 0xaa, 0x7e, 0xd5, 0xac, 0x26, 0x5c,
	0x7d, 0x6f, 0x4b, 0xe9, 0xfc, 0x3f, 0x48, 0x08, 0xf3, 0xbd, 0x77, 0x71, 0x21, 0x95, 0x60, 0x52,
	0xc8, 0x70, 0x43, 0x5f, 0xf4, 0x02, 0x1d, 0x28, 0x12, 0x59, 0xb8, 0xc2, 0xef, 0xc3, 0xdf, 0x08,
	0xdb, 0x0b, 0xca, 0xb0, 0xcc, 0xfc, 0x20, 0xee, 0xcc, 0xad, 0x2e, 0x43, 0xd5, 0xfa, 0x26, 0x2e,
	0x24, 0x77, 0xe9, 0x6d, 0x39, 0xd8, 0xba, 0xaa, 0xa9, 0xb5, 0xde, 0x79, 0x6a, 0xeb, 0x7f, 0x5a,
	0xf0, 0x6c, 0xd7, 0xba, 0xce, 0xd5, 0x60, 0xac, 0x27, 0xc2, 0x54, 0x7c, 0xed, 0x03, 0x7c, 0x9d,
	0x83, 0x7c, 0xdd, 0x26, 0xdf, 0xcf, 0x0d, 0xdf, 0x0e, 0xf1, 0x3d, 0xfe, 0x04, 0x53, 0xe5, 0xe2,
	0x6f, 0x17, 0x86, 0x94, 0xc0, 0x9c, 0x2e, 0xf3, 0x37, 0xd0, 0x3d, 0x8f, 0x22, 0x35, 0x76, 0xbe,
	0xdf, 0x78, 0xf9, 0xf4, 0x4c, 0x26, 0x2d, 0x94, 0x8c, 0x59, 0xfc, 0x13, 0x76, 0x0e, 0xdd, 0x4b,
	0x94, 0x0a, 0xe1, 0x01, 0xf5, 0xdb, 0x2d, 0x16, 0xf4, 0x98, 0x3f, 0x0a, 0x31, 0x08, 0x30, 0x11,
	0x1f, 0xf1, 0x11, 0x94, 0x97, 0x2d, 0x28, 0x2a, 0xe1, 0x9f, 0xb0, 0x2b, 0x18, 0x5e, 0xa2, 0xbc,
	0xb8, 0xff, 0x36, 0xde, 0x48, 0xcc, 0xd9, 0xeb, 0x56, 0x10, 0x9d, 0x9c, 0xbc, 0x3e, 0xd0, 0x8c,
	0x32, 0xa3, 0x7f, 0xc2, 0xde, 0xc1, 0xe8, 0x12, 0xa5, 0x52, 0x2e, 0x2e, 0x64, 0xbc, 0x3c, 0x8e,
	0xf5, 0xe9, 0x01, 0x2c, 0x2d, 0xbc, 0x7f, 0xc2, 0x2e, 0x01, 0xf4, 0x7d, 0xbf, 0x08, 0x0b, 0x6c,
	0xc1, 0xaa, 0x1e, 0x84, 0x47, 0x44, 0xfa, 0x0e, 0xc6, 0x06, 0xe8, 0x38, 0xc9, 0x27, 0x81, 0x5d,
	0xc1, 0x48, 0xd7, 0x99, 0xb7, 0xb5, 0xbd, 0x2f, 0x9d, 0x3c, 0x0e, 0x75, 0xf1, 0xea, 0x97, 0xda,
	0x8f, 0xda, 0xd7, 0x22, 0x11, 0x1f, 0x92, 0x22, 0xfb, 0xa0, 0x82, 0xeb, 0x2e, 0x25, 0xbe, 0xfc,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x72, 0x77, 0x02, 0xef, 0x09, 0x00, 0x00,
}
